# Generated by Django 5.1.6 on 2025-03-01 12:00

import apploan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0002_loan_paymentschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default=apploan.models.generate_loan_id, editable=False, max_length=20, unique=True),
        ),
    ]
